# Generated by Django 3.2.6 on 2021-09-06 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210828_0944'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='order.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transactionId',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
