# Generated by Django 3.2.6 on 2021-09-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210906_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(max_length=10)),
                ('discount', models.FloatField(default=0.0)),
                ('isValid', models.BooleanField(default=True)),
                ('usage', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='error',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='mode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
