# Generated by Django 3.2.6 on 2021-09-10 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
