# Generated by Django 3.2.6 on 2021-09-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilities',
            name='key',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
