# Generated by Django 3.2.6 on 2021-09-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_utilities_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=40)),
            ],
        ),
    ]
