# Generated by Django 3.2.6 on 2021-08-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=20)),
                ('discount', models.FloatField(default=0.0)),
                ('dimension', models.CharField(max_length=20)),
                ('weight', models.FloatField()),
            ],
        ),
    ]
