# Generated by Django 3.2.6 on 2021-08-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='max_stock',
            field=models.IntegerField(default=10000),
        ),
    ]
