# Generated by Django 3.2.6 on 2021-08-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_max_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='delivery_factor',
            field=models.FloatField(default=1),
        ),
    ]
