# Generated by Django 3.2.6 on 2021-08-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='view_count',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
