# Generated by Django 3.2.6 on 2021-08-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
