# Generated by Django 3.2.6 on 2021-09-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20210828_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=30, null=True),
        ),
    ]
