# Generated by Django 3.2.6 on 2021-09-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='breadth',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='height',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='length',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
