# Generated by Django 3.2.6 on 2021-09-09 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20210909_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='dimension',
        ),
    ]
