# Generated by Django 3.2.6 on 2021-09-09 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
