# Generated by Django 3.2.6 on 2021-09-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='outdated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
