# Generated by Django 3.2.6 on 2021-08-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210821_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUnverified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15, null=True, unique=True)),
                ('email', models.CharField(max_length=15, null=True, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'other')], max_length=2, null=True)),
                ('emailOtp', models.IntegerField(null=True)),
                ('mobileOtp', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
