# Generated by Django 3.2.6 on 2021-08-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210824_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userunverified',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userunverified',
            name='mobile',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
