# Generated by Django 3.2.6 on 2021-08-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210827_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userunverified',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='userunverified',
            name='last_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
