# Generated by Django 3.2.6 on 2021-08-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210827_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userunverified',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userunverified',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userunverified',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userunverified',
            name='district',
        ),
        migrations.RemoveField(
            model_name='userunverified',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='userunverified',
            name='state',
        ),
    ]
