# Generated by Django 3.2.6 on 2021-08-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210828_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='title',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
