# Generated by Django 3.2.6 on 2021-08-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('amount', models.FloatField()),
                ('delivery_charges', models.FloatField()),
                ('details', models.JSONField()),
            ],
        ),
    ]
