# Generated by Django 3.2.6 on 2021-08-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210822_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderId',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
