# Generated by Django 3.2.6 on 2021-08-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentMode',
            field=models.CharField(choices=[('C', 'COD'), ('O', 'ONLINE')], default='O', max_length=1),
            preserve_default=False,
        ),
    ]
