# Generated by Django 3.2.6 on 2021-09-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20210910_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='trackingUrl',
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
