# Generated by Django 3.2.6 on 2021-09-10 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210910_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='generated_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
