# Generated by Django 3.2.6 on 2021-09-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20210917_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cod_charges',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
