# Generated by Django 3.2.6 on 2021-08-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('_password', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=12)),
                ('books', models.BooleanField(default=0)),
                ('orders', models.BooleanField(default=0)),
                ('users', models.BooleanField(default=0)),
            ],
        ),
    ]
