# Generated by Django 3.2.6 on 2021-09-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20210830_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
