# Generated by Django 3.2.6 on 2021-09-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_manager_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='coupon',
            field=models.BooleanField(default=False),
        ),
    ]
